<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/**
 * Presentation-only assets for the standalone header/footer.
 */
function pv_v7_enqueue_presentation_assets() {
    $css = get_stylesheet_directory() . '/assets/css/pv-presentation.css';
    $js  = get_stylesheet_directory() . '/assets/js/pv-presentation.js';

    if ( is_file( $css ) ) {
        wp_enqueue_style(
            'pv-presentation',
            get_stylesheet_directory_uri() . '/assets/css/pv-presentation.css',
            array( 'pv-footer-v250', 'pv-header-v260' ),
            filemtime( $css )
        );
    }

    if ( is_file( $js ) ) {
        wp_enqueue_script(
            'pv-presentation',
            get_stylesheet_directory_uri() . '/assets/js/pv-presentation.js',
            array(),
            filemtime( $js ),
            true
        );
    }
}
add_action( 'wp_enqueue_scripts', 'pv_v7_enqueue_presentation_assets', 120 );

/**
 * Canonicalise legacy legal-page paths generated by older footer/template code.
 */
function pv_v7_canonicalise_legal_home_url( $url, $path ) {
    $map = array(
        '/kullanim-sartlari/'     => '/kullanim-kosullari/',
        '/kvkk-aydinlatma-metni/' => '/kvkk/',
        '/sorumluluk-reddi/'      => '/sorumluluk-reddi-beyani/',
    );

    $normalised = '/' . trim( (string) $path, '/' ) . '/';

    if ( isset( $map[ $normalised ] ) ) {
        return home_url( $map[ $normalised ] );
    }

    return $url;
}
add_filter( 'home_url', 'pv_v7_canonicalise_legal_home_url', 10, 2 );

/**
 * Preserve old public URLs as 301 aliases.
 */
function pv_v7_legal_legacy_redirects() {
    if ( is_admin() ) {
        return;
    }

    $request_path = isset( $_SERVER['REQUEST_URI'] )
        ? trim( (string) wp_parse_url( esc_url_raw( wp_unslash( $_SERVER['REQUEST_URI'] ) ), PHP_URL_PATH ), '/' )
        : '';

    $redirects = array(
        'kullanim-sartlari'     => '/kullanim-kosullari/',
        'kvkk-aydinlatma-metni' => '/kvkk/',
        'sorumluluk-reddi'      => '/sorumluluk-reddi-beyani/',
    );

    if ( isset( $redirects[ $request_path ] ) ) {
        wp_safe_redirect( home_url( $redirects[ $request_path ] ), 301 );
        exit;
    }
}
add_action( 'template_redirect', 'pv_v7_legal_legacy_redirects', 1 );
